{{#if compileNative}}
FROM amd64/alpine:3.19.1
COPY {{cliname}} /usr/local/bin/{{cliname}}
{{else}}
FROM openjdk:17
COPY {{cliname}}.jar /usr/local/bin/{{cliname}}.jar
COPY bin /usr/local/bin/{{cliname}}
{{/if}}
WORKDIR /home/{{cliname}}
RUN chmod +x /usr/local/bin/{{cliname}}
ENTRYPOINT ["{{cliname}}"]